Actualizando README SENAMHI
gaga4@JOSE MINGW64 ~/Desktop/Trabajo final LP2/Trabajo final (main|MERGING)
$ git commit -m "Merge SENAMHI into main (resolve README conflict)"
[main 74bb750] Merge SENAMHI into main (resolve README conflict)

gaga4@JOSE MINGW64 ~/Desktop/Trabajo final LP2/Trabajo final (main)
$ git push origin main
To https://github.com/Sebas20050700/PIPELINE_AERO-METEREOLOGICO.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/Sebas20050700/PIPELINE_AERO-METEREOLOGICO.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

gaga4@JOSE MINGW64 ~/Desktop/Trabajo final LP2/Trabajo final (main|MERGING)
$ git commit -m "Merge SENAMHI into main (resolve README conflict)"
[main 74bb750] Merge SENAMHI into main (resolve README conflict)

gaga4@JOSE MINGW64 ~/Desktop/Trabajo final LP2/Trabajo final (main)
$ git push origin main
To https://github.com/Sebas20050700/PIPELINE_AERO-METEREOLOGICO.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/Sebas20050700/PIPELINE_AERO-METEREOLOGICO.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.